### Create a user with a factory new token
POST http://localhost:6609/pushlog/user
Content-Type: application/json

# returns BAD_REQUEST when displayname is not given or displayname length is greater than 32
{
  "displayname": "TestAccount"
}

### Get all the data about a user
GET http://localhost:6609/pushlog/user/uCQOc_TNRKsgu_le3gE7EKZtpEpy8HOeU_Q5n1B9EvjzyB0a-8dqndqieqG16JUjMcuHqPlgzna6Mg2fZ06et2U0Mc3VklfOrGZX8zN_DyFVBquf6PD_xhpep-kajBxifAK3MttzdruLXXspl4Rqu6dE16-tSJDPAJOSIiRK7R2e-k8PLXp_zy--5y3IQxBa-jeij_2z-vYdGlgu_HaOtlddAiOX6019lEg5vv7lcWkaNph9PudwglTrQSzjl8KsGcqw-_tyoJEMLbSg1wPWXwrOXY1ue22eF0aXhmw5a_5-rfeQE99-DtKsrIPsfBWhrUnTQxxD6Zlo-cmQ2AK62LYDswMXrvxCYq4ZZqYDrr1u7_iMnDQatRoe2xrls_GDCpuGVIp5bXdkq8sI7AyrwZ287xBOUrLAW5fkI507qRMoqvfvcJFyV9zFurthLxNz-gU-jocASEAnH2xJ6u5td0uSAY4cfiO3XYr7G09ahplsDZ2-N2eYu7yCQZsqAMaVtd_8eUgQ9OG9r7tgNhnLLtIEjr0bR5o8VRVXBVWkwGMo84_Y2PBscC7WKSCMRe0Ut53ePFeKu1wj8jnfPhIYB5dEwN5t2s7xzpsXLu1_qKiaz8NQsBZc2kAXpKUKW8tGSNTUIxfGXdkCh8ejTQSxaEfTzI9rAl6aFQpfzkcqJ9Y=

### Create a new log
POST http://localhost:6609/pushlog/log/
Content-Type: application/json

# returns BAD_REQUEST when displayname is not given or displayname length is greater than 32
# reutrns BAD_REQUEST when token is not given
# returns NOT_FOUND when the user associated to the token does not exist
{
  "displayname": "TestLog",
  "token": "uCQOc_TNRKsgu_le3gE7EKZtpEpy8HOeU_Q5n1B9EvjzyB0a-8dqndqieqG16JUjMcuHqPlgzna6Mg2fZ06et2U0Mc3VklfOrGZX8zN_DyFVBquf6PD_xhpep-kajBxifAK3MttzdruLXXspl4Rqu6dE16-tSJDPAJOSIiRK7R2e-k8PLXp_zy--5y3IQxBa-jeij_2z-vYdGlgu_HaOtlddAiOX6019lEg5vv7lcWkaNph9PudwglTrQSzjl8KsGcqw-_tyoJEMLbSg1wPWXwrOXY1ue22eF0aXhmw5a_5-rfeQE99-DtKsrIPsfBWhrUnTQxxD6Zlo-cmQ2AK62LYDswMXrvxCYq4ZZqYDrr1u7_iMnDQatRoe2xrls_GDCpuGVIp5bXdkq8sI7AyrwZ287xBOUrLAW5fkI507qRMoqvfvcJFyV9zFurthLxNz-gU-jocASEAnH2xJ6u5td0uSAY4cfiO3XYr7G09ahplsDZ2-N2eYu7yCQZsqAMaVtd_8eUgQ9OG9r7tgNhnLLtIEjr0bR5o8VRVXBVWkwGMo84_Y2PBscC7WKSCMRe0Ut53ePFeKu1wj8jnfPhIYB5dEwN5t2s7xzpsXLu1_qKiaz8NQsBZc2kAXpKUKW8tGSNTUIxfGXdkCh8ejTQSxaEfTzI9rAl6aFQpfzkcqJ9Y="
}

###
POST http://localhost:6609/pushlog/log/info
Content-Type: application/json

{
  "token": "CjAe45YnGMJsAFVDHl9HuvTq9KLbt97WqpCO4XQd1GgNo9mydXCkedrAr1J8DFai_7OPDPsWKvx8VS-me4xGnG3_MQPC8gOHyLuG9u8jkHs5etn_2CgBLFLQu2tG6mkscF_6xh93mBg0Z3weGXoS8rSyp3QlBxEU-BUAedJG9K1b6ysp-mm5YHvSqicYSaLB-bcZJpaqR9JnGCcZpdV4TYWnQ7389BlI-cmiG_2zmGeSzGkoqZShftatrTzN7AQMBk64Yf_9GL2ScCvq220MWU2XCdiEv2Y-W6cCzhLFhUFH6rN5PhIy0G1Ff5QFEIJQwSr6154TbFxss3hkAKLOkqxzVHfAyYDOYTfP-4eirN_kQwvAI3quX92jDWiEz5GMVrfJEeCSicvadsBPaSL_1E4dvxmpjjQeoshYAez4jJ0rhM1CbMlSYKjiRd1dt2QomLimfdWwOdmU_2hgqaQJlIjzSXvmfBWGs9vYuwchMfqVw7fTAb90GSmrCqB38IqLCdm4fvdpXrA7tlygUtzCVq5hbm_qiYKGNPBSBAmQZbpX4awgw2Uoenqrlm1ugvaySC8rzKsVpmccw_fNPjoKEXmrO-X9DVSctdZF43AzhDaFvwv7Qv8mS8Md61RqtYOOua6K5m4csc6Kdg8B-R-mIKsfiCAOShIEbS_iQA0Zg50=",
  "value": "test log"
}

###
GET http://localhost:6609/pushlog/log/CjAe45YnGMJsAFVDHl9HuvTq9KLbt97WqpCO4XQd1GgNo9mydXCkedrAr1J8DFai_7OPDPsWKvx8VS-me4xGnG3_MQPC8gOHyLuG9u8jkHs5etn_2CgBLFLQu2tG6mkscF_6xh93mBg0Z3weGXoS8rSyp3QlBxEU-BUAedJG9K1b6ysp-mm5YHvSqicYSaLB-bcZJpaqR9JnGCcZpdV4TYWnQ7389BlI-cmiG_2zmGeSzGkoqZShftatrTzN7AQMBk64Yf_9GL2ScCvq220MWU2XCdiEv2Y-W6cCzhLFhUFH6rN5PhIy0G1Ff5QFEIJQwSr6154TbFxss3hkAKLOkqxzVHfAyYDOYTfP-4eirN_kQwvAI3quX92jDWiEz5GMVrfJEeCSicvadsBPaSL_1E4dvxmpjjQeoshYAez4jJ0rhM1CbMlSYKjiRd1dt2QomLimfdWwOdmU_2hgqaQJlIjzSXvmfBWGs9vYuwchMfqVw7fTAb90GSmrCqB38IqLCdm4fvdpXrA7tlygUtzCVq5hbm_qiYKGNPBSBAmQZbpX4awgw2Uoenqrlm1ugvaySC8rzKsVpmccw_fNPjoKEXmrO-X9DVSctdZF43AzhDaFvwv7Qv8mS8Md61RqtYOOua6K5m4csc6Kdg8B-R-mIKsfiCAOShIEbS_iQA0Zg50=
Content-Type: application/json
